package Client;

import Config.Connector;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonatan Samuel Martinez Hernandez ficha 2675859
 *
 * Evidencia de desempeño:
 *
 * Codificación de módulos del software según requerimientos del proyecto
 * GA7-220501096-AA2-EV01
 *
 * análisis y desarrollo de software
 *
 */
public class ClientView extends javax.swing.JFrame {

    // create a new instance of controller for client
    ClientController clientController = new ClientController();
    // create a new instance of connector
    Connector connector = new Connector();

    DefaultTableModel model;

    /**
     * Creates new form ClientForm
     */
    public ClientView() {

        // Set the controller for client
        initComponents();
        setLocationRelativeTo(null);
        welcomeMessage();
        // makes a request for get the list of registered clients in the data base at the start of the programm
        consultDataBase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        intClientId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClientPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DeleteClient = new javax.swing.JButton();
        updateClient = new javax.swing.JButton();
        addClient = new javax.swing.JButton();
        txtClientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClientLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setForeground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("Client Manager System");

        intClientId.setEditable(false);

        jLabel1.setText("Id");

        jLabel5.setText("Phone");

        DeleteClient.setText("Delete");
        DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientActionPerformed(evt);
            }
        });

        updateClient.setText("Modify");
        updateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClientActionPerformed(evt);
            }
        });

        addClient.setText("Add");
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Last name");

        jLabel4.setText("Desarrollado por Jhonatan Samuel Martinez Hernandez");

        jLabel7.setText("Análisita y Desarrollador de Software");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(intClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(txtClientName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(addClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateClient)
                .addGap(12, 12, 12)
                .addComponent(DeleteClient)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(intClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClient)
                    .addComponent(DeleteClient)
                    .addComponent(updateClient))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "name", "Last name", "Phonel"
            }
        ));
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(118, 118, 118)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // wellcome message and self introduction of me
    public void welcomeMessage() {
        JOptionPane.showMessageDialog(null, "Wellcome to my system. my name is Jhonatan Samuel Martinez. Software Developer.");
    }

    /*this method allows us to clean the table row that way 
        we don't repeat data when listing records from data base
     */
    public void cleanTable() {
        //  use a loop to go through all the rows in the table
        for (int i = 0; i < clientTable.getRowCount(); i++) {
            // remove each row that the table could have
            model.removeRow(i);
            i = i - 1;
        }
    }

    // this method make a request for all the clients registered in the data base and print them in the console
    void consultDataBase() {

        // add the connector to be use with the controller
        this.clientController.addConnector(connector);

        // gets the model of the table created for clients 
        model = (DefaultTableModel) clientTable.getModel();
// use here the controller for clients to get a list of all the clients from the data base
        List<ClientModel> list = this.clientController.getAllClients();
// here i instanciated an object that will serve me to represent a row in the table
        Object[] row = new Object[4];
// loop throught all the list of clients and get the id, name, last name and phone of each of them.
// after that i assign them to a position ( column ) in the row
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getLastName();
            row[3] = list.get(i).getPhone();
// later. here i add the row to the model of the JTabl
            model.addRow(row);
        }
// finally here i have set the new model to the table model so i will see all the listed clients 
        clientTable.setModel(model);
    }


    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        // TODO add your handling code here:
        // get the selected row by the user
        int row = clientTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Error when getting data of selected row");
            System.out.println("Error when getting data of selected row. the row number is " + row);

        } else {
            // get values of each column of the selected row 
            // assing the values to variables
            String ClientId = clientTable.getModel().getValueAt(row, 0).toString();
            String ClientName = clientTable.getModel().getValueAt(row, 1).toString();
            String ClientLastName = clientTable.getModel().getValueAt(row, 2).toString();
            String ClientPhone = clientTable.getModel().getValueAt(row, 3).toString();
            // set the values of each column to their corresponding fields in the form
            intClientId.setText(ClientId);
            txtClientName.setText(ClientName);
            txtClientLastName.setText(ClientLastName);
            txtClientPhone.setText(ClientPhone);
            System.out.println("user data of selected row " + row + " assign to the form ");
            System.out.println("Client name: " + ClientName + " phone: " + ClientPhone);

        }


    }//GEN-LAST:event_clientTableMouseClicked

    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed
        // button for create client
        // add the connector to be use with the controller
        this.clientController.addConnector(connector);

        // checks if all the fields are completed
        if (txtClientName.getText().equals("") || txtClientLastName.getText().equals("") || txtClientPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");

        } else {
            // create a new instance of client
            ClientModel client = new ClientModel();
            // Set field values to client attibutes
            client.setName(txtClientName.getText());
            client.setLastName(txtClientLastName.getText());
            client.setPhone(txtClientPhone.getText());
            // call the client controller class
            clientController.saveClient(client);
        }

        // cleans the table view
        this.cleanTable();
        // make a request to data base for the new list of clients
        this.consultDataBase();

    }//GEN-LAST:event_addClientActionPerformed

    private void updateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClientActionPerformed
        // TODO add your handling code here:

        // add the connector to be use with the controller
        this.clientController.addConnector(connector);

        // checks if all the fields are completed
        if (txtClientName.getText().equals("") || txtClientLastName.getText().equals("") || txtClientPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser llenar para actualizar la información");

        } else {
            // get the client id from the text field form and convert it to Long
            Long id = Long.parseLong(intClientId.getText());

            // Set field values to client attibutes
            String name = (txtClientName.getText());
            String lastName = (txtClientLastName.getText());
            String phone = (txtClientPhone.getText());

            // instancia a client
            ClientModel clientTemp = new ClientModel();
            // assign the values of the variables
            clientTemp.setId(id);
            clientTemp.setName(name);
            clientTemp.setLastName(lastName);
            clientTemp.setPhone(phone);

            // call the client controller class
            clientController.UpdateClient(clientTemp);
            System.out.println("el id del cliente es " + id);

            // cleans the table view
            this.cleanTable();
            // make a request to data base for the new list of clients
            this.consultDataBase();

        }
    }//GEN-LAST:event_updateClientActionPerformed

    private void DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientActionPerformed
        // TODO add your handling code here:

        // checks if any client information is present
        // if data fields are empty displays an error
        if (intClientId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No client selected. Please select one from the table.");

            // else if all the fiels are completed and clients data in present, deletes the client by its id
        } else {
            Long id = Long.parseLong(intClientId.getText());
            String clientName = txtClientName.getText();
            clientController.deleteClientById(id, clientName);

            // cleans the table view
            this.cleanTable();
            // make a request to data base for the new list of clients
            this.consultDataBase();
        }

    }//GEN-LAST:event_DeleteClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteClient;
    private javax.swing.JButton addClient;
    private javax.swing.JTable clientTable;
    private javax.swing.JTextField intClientId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtClientLastName;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientPhone;
    private javax.swing.JButton updateClient;
    // End of variables declaration//GEN-END:variables
}

/**
 *
 * @author Jhonatan Samuel Martinez Hernandez ficha 2675859
 *
 * Evidencia de desempeño:
 *
 * Codificación de módulos del software según requerimientos del proyecto
 * GA7-220501096-AA2-EV01
 *
 * análisis y desarrollo de software
 *
 */
